import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full bg-amber-500 text-slate-900 shadow-md">
          <nav className="max-w-xl mx-auto px-4 py-3 flex items-center justify-between gap-3">
            <Link
              href="/entry"
              className="flex-1 text-center text-xs font-extrabold tracking-wide rounded-full bg-amber-50/90 text-amber-900 px-3 py-2 active:scale-95 transition-transform"
            >
              ENTRY GATE
            </Link>
            <Link
              href="/food"
              className="flex-1 text-center text-xs font-extrabold tracking-wide rounded-full bg-amber-50/90 text-amber-900 px-3 py-2 active:scale-95 transition-transform"
            >
              FOOD COUNTER
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
